// Issue #133 Part 2 — print/PDF export of a roadmap via a dedicated print
// stylesheet + the browser's native print-to-PDF, not a client-side PDF
// library (root CLAUDE.md's "no build step, no bundler" constraint; a printed
// checklist doesn't need pixel-perfect PDF control). Builds a plain,
// print-only DOM snapshot from the current roadmap and appends it to
// document.body just long enough to print, then removes it — app.css's
// `@media print` rules hide everything else and show only `.print-roadmap`.
import { el, isValidUrl } from '../dom.js';
import { openModal } from '../components/modal.js';
import { getTemplate } from '../../data/templates/index.js';
import { createBrandMark } from '../components/brand.js';

// Read from `window.location` at print time, not hardcoded — a real bug:
// this used to be a literal `'ascent-app.com'` string, which was correct in
// production but printed `localhost:4173` verbatim during local dev, and
// would go stale the moment the real production domain ever changed (a
// custom domain, a Firebase Hosting site rename, etc.), silently printing
// the wrong URL on every export until someone remembered to update this
// file. `window.location.host` always reflects wherever the app is actually
// being served from — dev, a PR preview, or production — with nothing to
// keep in sync by hand.
function printSiteUrl() {
  return window.location.host;
}

function resolveRoadmapTitle(snapshot) {
  const custom = (snapshot.customRoadmaps || []).find(r => r.id === snapshot.activeTemplateId);
  if (custom) return custom.title;
  return getTemplate(snapshot.activeTemplateId)?.name || 'Roadmap';
}

// Repeats on every physical page via the browser's native `<thead>`/`<tfoot>`
// table-repeat behavior — not `position: fixed`. An earlier version used
// `position: fixed` header/footer divs, which Chrome/Firefox do repeat per
// page, but positioning them clear of the flowing content requires reserved
// space that repeats identically on *every* page too. `.print-roadmap`'s own
// padding only reserves space once, at the top/bottom of the whole flowed
// document, so pages after the first rendered content flush against the page
// edge, underneath the fixed header (reported live via a 47-page multi-phase
// PDF export). A follow-up `@page` margin fix was tried next, but Chromium's
// print pagination positions `position: fixed` elements relative to the
// *content* box (inside the page margins), not the page edge — so a fixed
// header at `top: 0` lands at the same coordinate flowing content starts at,
// reproducing the identical overlap regardless of how large the margin is.
// A real HTML `<table>` with `<thead>`/`<tfoot>` is the only technique
// verified (via a real multi-page `page.pdf()` render, not just visual
// inspection) to both repeat AND correctly reserve space on every page in
// Chromium — this is the standard, spec-backed cross-browser print-repeat
// mechanism, not a `position: fixed` approximation of it.
function buildPrintHeaderRow() {
  return el('thead', {}, [
    el('tr', {}, [
      el('td', {}, [
        el('div', { className: 'print-page-header' }, [
          el('div', { className: 'print-brand brand' }, createBrandMark({ tagline: 'Engineer your next move.' }))
        ])
      ])
    ])
  ]);
}

function buildPrintFooterRow() {
  return el('tfoot', {}, [
    el('tr', {}, [
      el('td', {}, [
        el('div', { className: 'print-page-footer' }, [
          el('span', { text: `Generated by ${printSiteUrl()}` })
        ])
      ])
    ])
  ]);
}

function buildPrintNode(snapshot, { includeNotes }) {
  const phaseNodes = (snapshot.phases || []).map(phase => {
    const items = Object.values(snapshot.allItems || {})
      .filter(item => !item.deleted && item.phase === phase.title);
    const sectionTitles = [...new Set(items.map(item => item.section))];
    const sectionNodes = sectionTitles.map(sectionTitle => {
      const sectionItems = items.filter(item => item.section === sectionTitle);
      return el('div', { className: 'print-section' }, [
        el('h3', { className: 'print-section-title', text: sectionTitle }),
        el('ul', { className: 'print-item-list' }, sectionItems.map(item => renderPrintItem(item, includeNotes)))
      ]);
    });
    return el('section', { className: `print-phase print-phase-${phase.priority}` }, [
      el('h2', { className: 'print-phase-title', text: `${phase.title} (${phase.priority})` }),
      ...sectionNodes
    ]);
  });

  return el('table', { className: 'print-roadmap' }, [
    buildPrintHeaderRow(),
    buildPrintFooterRow(),
    el('tbody', {}, [
      el('tr', {}, [
        el('td', {}, [
          el('h1', { className: 'print-roadmap-title', text: resolveRoadmapTitle(snapshot) }),
          ...phaseNodes
        ])
      ])
    ])
  ]);
}

// A faint, blurred full-page watermark (logo + wordmark) repeating behind the
// content on every printed page — `position: fixed` is the right tool here,
// unlike the header/footer above: those needed *space reserved* for them
// (which is what `position: fixed` can't do per-page, see the block comment
// above), but a watermark is deliberately *behind* the flowing content and
// is allowed to overlap it, so the `<thead>`/`<tfoot>` repeat mechanism isn't
// needed — `position: fixed` already repeats correctly per page on its own.
// Kept as a single large centered mark rather than a tiled pattern so it
// reads as a discreet page identifier, not a distracting texture.
function buildPrintWatermark() {
  return el('div', { className: 'print-watermark' }, [
    el('div', { className: 'print-watermark-mark' }, createBrandMark({ tagline: undefined }))
  ]);
}

function renderPrintItem(item, includeNotes) {
  const resourceNodes = (item.resources || [])
    .filter(resource => isValidUrl(resource?.url))
    .map(resource => el('div', { className: 'print-resource', text: `${resource.label}: ${resource.url}` }));

  const children = [
    el('span', { className: 'print-check-glyph', text: item.done ? '☑' : '☐' }),
    el('span', { className: 'print-item-title', text: ` ${item.title} ` }),
    el('span', { className: `print-priority-badge print-priority-${item.priority}`, text: item.priority })
  ];
  if (includeNotes && item.notes) {
    children.push(el('div', { className: 'print-item-notes', text: item.notes }));
  }
  resourceNodes.forEach(node => children.push(node));

  return el('li', { className: 'print-item' }, children);
}

// Shared by both print entry points — the app's own "Print roadmap…" menu
// item (below) and dashboard.js's native/OS-print fallback (issue #254/#255)
// — so the printed output is visually identical no matter how print was
// triggered or which device it's on. Building the clean `.print-roadmap`
// snapshot is what makes the browser's own chrome-hiding CSS unnecessary:
// once this table (plus the watermark) is the only thing `.print-mode`
// shows, there's nothing left of the live dashboard — checkboxes, Edit
// buttons, "Add a custom topic…" inputs — for a native/OS print trigger to
// leak through, which is exactly what issue #262 found happening when the
// native fallback only reset layout via CSS instead of mounting this same
// snapshot. Also sets `document.title` to the roadmap's own name for the
// duration of the print/PDF-save so the browser's "Save as PDF" filename
// reflects the roadmap, not the app's own always-"Ascent" `<title>`.
export function mountPrintSnapshot(store, includeNotes) {
  const snapshot = store.getSnapshot();
  const watermark = buildPrintWatermark();
  const node = buildPrintNode(snapshot, { includeNotes });
  const previousTitle = document.title;
  // Watermark first so it paints underneath the roadmap table in DOM/paint
  // order — `.print-watermark`'s own `z-index` (app.css) is the real
  // guarantee, this ordering is just belt-and-suspenders.
  document.body.appendChild(watermark);
  document.body.appendChild(node);
  document.body.classList.add('print-mode');
  document.title = resolveRoadmapTitle(snapshot);

  return function unmount() {
    watermark.remove();
    node.remove();
    document.body.classList.remove('print-mode');
    document.title = previousTitle;
  };
}

// `afterprint` alone is unreliable on mobile: `window.print()` blocks
// synchronously on desktop until the OS dialog is dismissed, so `afterprint`
// only fires once the print engine has already captured the page — but on
// Android Chrome, printing hands off to the OS's print framework
// asynchronously and `afterprint` fires almost immediately, well before the
// real snapshot is taken. Tearing down the print DOM at that point strips it
// before the OS has actually captured it, so the printed output shows the
// live dashboard instead. `matchMedia('print')` reflects the browser's
// actual print-media state rather than a hook Chromium can fire early, so
// `unmount` only runs once print media has genuinely stopped matching.
export function attachPrintCleanup(unmount) {
  const printMediaQuery = window.matchMedia('print');
  let done = false;
  function cleanup() {
    if (done) return;
    done = true;
    unmount();
    window.removeEventListener('afterprint', handleAfterPrint);
    printMediaQuery.removeEventListener('change', handlePrintMediaChange);
  }
  function handlePrintMediaChange(e) {
    if (!e.matches) cleanup();
  }
  function handleAfterPrint() {
    if (!printMediaQuery.matches) cleanup();
  }
  printMediaQuery.addEventListener('change', handlePrintMediaChange);
  window.addEventListener('afterprint', handleAfterPrint);
}

function printSnapshot(store, includeNotes) {
  const unmount = mountPrintSnapshot(store, includeNotes);
  attachPrintCleanup(unmount);
  window.print();
}

// Asks whether to include notes (off by default — same privacy-conscious
// default as roadmap sharing, issue #131) before printing.
export function triggerRoadmapPrint(store) {
  let includeNotes = false;
  const checkbox = el('input', {
    type: 'checkbox',
    id: 'print-include-notes',
    onChange: e => { includeNotes = e.target.checked; }
  });

  const { close } = openModal({
    ariaLabel: 'Print roadmap',
    content: [
      el('h2', { text: 'Print roadmap' }),
      el('p', { text: 'This opens your browser’s print dialog, where you can save the roadmap as a PDF.' }),
      el('label', { className: 'print-include-notes-row' }, [
        checkbox,
        el('span', { text: 'Include notes' })
      ]),
      el('div', { className: 'confirm-dialog-actions' }, [
        el('button', { type: 'button', className: 'btn btn-secondary', text: 'Cancel', onClick: () => close() }),
        el('button', {
          type: 'button',
          className: 'btn btn-primary',
          text: 'Print',
          onClick: () => {
            close();
            printSnapshot(store, includeNotes);
          }
        })
      ])
    ]
  });
}
