import { el } from '../dom.js';
import { createBrandMark, createBrandWordmark } from '../components/brand.js';
import { createIcon } from '../components/icons.js';
import { svgIcon } from '../utils/svg.js';
import { TEMPLATES } from '../../data/templates/index.js';

// De-duplicated onto the shared svgIcon() helper (issue #107) — was a local
// copy-pasted svgEl/iconSvg pair, same pattern authMarketingPanel.js/
// progressRing.js used to have independently. No visual change: same 26px
// size, same shape data.
function iconSvg(shapes) {
  return svgIcon(shapes, { size: 26 });
}

const ICONS = {
  template: () => iconSvg([
    { tag: 'rect', x: '4', y: '4', width: '7', height: '7', rx: '2', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8' },
    { tag: 'rect', x: '13', y: '4', width: '7', height: '7', rx: '2', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8' },
    { tag: 'rect', x: '4', y: '13', width: '7', height: '7', rx: '2', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8' },
    { tag: 'rect', x: '13', y: '13', width: '7', height: '7', rx: '2', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8' }
  ]),
  build: () => iconSvg([
    { d: 'M14.5 4.5l5 5-9 9L5 20l1.5-5.5z', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8', 'stroke-linecap': 'round', 'stroke-linejoin': 'round' },
    { d: 'M12.5 6.5l5 5', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8', 'stroke-linecap': 'round' }
  ]),
  pick: () => iconSvg([
    { tag: 'circle', cx: '12', cy: '12', r: '9', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8' },
    { d: 'M12 7v5l3.5 2', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8', 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }
  ]),
  track: () => iconSvg([
    { tag: 'rect', x: '4', y: '4', width: '16', height: '16', rx: '5', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8' },
    { d: 'M8 12.5l2.5 2.5L16.5 9', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8', 'stroke-linecap': 'round', 'stroke-linejoin': 'round' }
  ]),
  stay: () => iconSvg([
    { tag: 'circle', cx: '12', cy: '12', r: '8', fill: 'none', stroke: 'currentColor', 'stroke-width': '1.8' },
    { tag: 'circle', cx: '12', cy: '12', r: '3.2', fill: 'currentColor' }
  ])
};

// Two cards, not three — the original spec's third card ("Drive sync") was
// dropped when #5 (Google Drive backend) closed as not planned; inventing a
// replacement feature just to keep a three-card grid would be marketing copy
// for something that doesn't exist, so this stays at two rather than three.
const FEATURES = [
  {
    icon: ICONS.template,
    title: 'Start with a template',
    text: `Pick from ${TEMPLATES.length} starter roadmaps — Java Backend, Frontend, Data Science, GenAI/Agentic AI, and more — each broken into phases, sections, and prioritized topics.`
  },
  {
    icon: ICONS.build,
    title: 'Build your own',
    text: 'Create a roadmap from scratch, or import one generated by AI from a topic you describe — same phase/section structure, fully editable.'
  }
];

const STEPS = [
  { icon: ICONS.pick, title: 'Pick a starting point', text: 'Choose a starter template, build your own, or import one with AI.' },
  { icon: ICONS.track, title: 'Track every topic', text: 'Check items off by phase and priority as you learn, revise, or build.' },
  { icon: ICONS.stay, title: 'Stay on track', text: 'Priority filters and Daily Todos keep today’s work front and center, synced across every device.' }
];

// No fabricated customer quote here, on purpose — same call already made for
// the auth marketing panel (Phase 5): a fake testimonial reads as deceptive
// on a product moving toward real paying users. This is a real, derived stat
// instead of an invented "social proof" quote.
function landingProofLine() {
  return `${TEMPLATES.length} starter roadmaps and counting — or build your own from scratch.`;
}

function scrollToSection(id) {
  const target = document.getElementById(id);
  if (!target) return;
  const reduceMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  target.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'start' });
}

function buildNav() {
  const featuresLink = el('button', { type: 'button', className: 'landing-nav-link', text: 'Features' });
  featuresLink.addEventListener('click', () => scrollToSection('landing-features'));
  const stepsLink = el('button', { type: 'button', className: 'landing-nav-link', text: 'How it works' });
  stepsLink.addEventListener('click', () => scrollToSection('landing-steps'));

  return el('header', { className: 'landing-nav' }, [
    el('a', { className: 'brand', href: '#/signin' }, createBrandMark()),
    el('nav', { className: 'landing-nav-links', 'aria-label': 'Page sections' }, [featuresLink, stepsLink]),
    el('div', { className: 'landing-nav-actions' }, [
      el('a', { className: 'btn btn-ghost', href: '#/signin', text: 'Sign in' }),
      el('a', { className: 'btn btn-primary', href: '#/signup', text: 'Start for free' })
    ])
  ]);
}

// Decorative mock of the dashboard — plain el()-built blocks, not an
// external screenshot asset. Keeps the "no build step, no bundler, no
// external dependency" convention intact instead of requiring a committed
// PNG (and a Playwright-based generation step) for one hero graphic.
//
// issue #155 — the mock card now sits inside a `position: relative`
// wrapper so `.landing-mock-badge` can overlap its top-left corner (the
// reference's "badge floats partially outside the card it's labeling, not
// fully inside it" detail) via absolute positioning against that wrapper,
// not the card itself. The badge text is a real, already-shipped Ascent
// behavior ("Autosaved" — the same word `itemPanel.js`'s `.notes-status`
// already uses, issue #136 Phase 2), not an invented claim.
function buildHeroMock() {
  // Fill widths are a capped set of discrete CSS classes (landing-mock-fill-1
  // through -4), not a per-element inline style — see the "Never set an
  // inline style attribute" convention (root CLAUDE.md / ui-styling rules).
  const rows = [1, 2, 3, 4].map(n => el('div', { className: 'landing-mock-row' }, [
    el('span', { className: 'landing-mock-check', 'aria-hidden': 'true' }),
    el('span', { className: 'landing-mock-bar' }, [el('span', { className: `landing-mock-bar-fill landing-mock-fill-${n}` })])
  ]));
  return el('div', { className: 'landing-hero-mock', 'aria-hidden': 'true' }, [
    el('div', { className: 'landing-mock-card' }, [
      el('div', { className: 'landing-mock-head' }, [
        el('span', { className: 'landing-mock-dot' }),
        el('span', { className: 'landing-mock-dot' }),
        el('span', { className: 'landing-mock-dot' })
      ]),
      el('div', { className: 'landing-mock-body' }, rows)
    ]),
    el('span', { className: 'pill-icon landing-mock-badge' }, [
      createIcon('sparkle', { size: 'xs' }),
      el('span', { text: 'Autosaved' })
    ])
  ]);
}

// issue #155 — status-pill badge above the headline (the reference's "NEW ·
// AI Nodes Clustering ready in beta!" pattern) and a two-tone headline
// (first phrase solid --ink, second muted, both same weight/size — the
// reference's mixed-emphasis treatment). Badged feature is AI-assisted
// import, a real already-shipped capability (see FEATURES below), not an
// invented "AI-powered" product claim.
function buildHero() {
  return el('section', { className: 'landing-hero' }, [
    el('div', { className: 'landing-hero-copy' }, [
      el('span', { className: 'pill-icon landing-hero-badge' }, [
        createIcon('sparkle', { size: 'xs' }),
        el('span', { text: 'AI-assisted roadmap import' })
      ]),
      el('h1', { className: 'landing-hero-title' }, [
        el('span', { text: 'Engineer your ' }),
        el('span', { className: 'landing-hero-title-muted', text: 'next move.' })
      ]),
      el('p', { className: 'landing-hero-subtitle', text: 'The roadmap tracker for anyone learning, revising, or leveling up. Pick a starting point, track every topic, and always know what’s next.' }),
      el('div', { className: 'landing-hero-actions' }, [
        el('a', { className: 'btn btn-primary btn-lg', href: '#/signup', text: 'Start for free' }),
        el('a', { className: 'btn btn-outline btn-lg', href: '#/signin', text: 'Sign in' })
      ]),
      el('p', { className: 'landing-hero-stat', text: landingProofLine() })
    ]),
    buildHeroMock()
  ]);
}

function buildFeatures() {
  return el('section', { className: 'landing-features', id: 'landing-features' }, [
    el('h2', { className: 'landing-section-title', text: 'Two ways to start' }),
    el('div', { className: 'landing-feature-grid' }, FEATURES.map(f => el('div', { className: 'feature-card' }, [
      el('span', { className: 'feature-card-icon', 'aria-hidden': 'true' }, [f.icon()]),
      el('h3', { className: 'feature-card-title', text: f.title }),
      el('p', { className: 'feature-card-text', text: f.text })
    ])))
  ]);
}

function buildSteps() {
  return el('section', { className: 'landing-steps', id: 'landing-steps' }, [
    el('h2', { className: 'landing-section-title', text: 'How it works' }),
    el('ol', { className: 'landing-steps-list' }, STEPS.map((s, i) => el('li', { className: 'step-card' }, [
      el('span', { className: 'step-card-number', text: String(i + 1) }),
      el('span', { className: 'step-card-icon', 'aria-hidden': 'true' }, [s.icon()]),
      el('h3', { className: 'step-card-title', text: s.title }),
      el('p', { className: 'step-card-text', text: s.text })
    ])))
  ]);
}

function buildCta() {
  return el('section', { className: 'landing-cta' }, [
    el('h2', { className: 'landing-cta-title', text: 'Ready to engineer your next move?' }),
    el('a', { className: 'btn btn-primary btn-lg', href: '#/signup', text: 'Start for free' })
  ]);
}

// No hardcoded brand-name string here (root CLAUDE.md's brand rule) — the
// brand mark above already names the product, so the copyright line doesn't
// repeat it. issue #155 — a giant, low-opacity `createBrandWordmark()`
// bleeds off the bottom edge as decoration (the reference's footer motif) —
// reuses the same wordmark component every other brand usage in the app
// does, not a second hardcoded 'Ascent' string, and is `aria-hidden` since
// it's pure decoration, not a second real heading.
function buildFooter() {
  return el('footer', { className: 'landing-footer' }, [
    el('span', { className: 'brand' }, createBrandMark()),
    el('p', { className: 'landing-footer-copy', text: `© ${new Date().getFullYear()} · Engineer your next move.` }),
    el('div', { className: 'landing-footer-ghost', 'aria-hidden': 'true' }, [createBrandWordmark()])
  ]);
}

// Marketing page shown at '#/' to signed-out visitors (issue #6 Phase 6);
// main.js routes an already-signed-in user straight to '/app' before this
// ever renders, so this function never needs to check `user` itself.
export function renderLanding(app) {
  // Issue #6 Phase 9 — id="main-content"/tabindex="-1" is the skip link's
  // jump target (index.html), so Tab from page load can bypass the nav bar
  // straight to the hero.
  const node = el('div', { className: 'landing-page' }, [
    buildNav(),
    el('main', { id: 'main-content', tabindex: '-1' }, [
      buildHero(),
      buildFeatures(),
      buildSteps(),
      el('section', { className: 'landing-proof' }, [
        el('p', { className: 'landing-proof-text', text: landingProofLine() })
      ]),
      buildCta()
    ]),
    buildFooter()
  ]);
  app.replaceChildren(node);
}
